name: edusphere_mobile
description: "To be added soon"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  build_runner: ^2.4.13
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.8
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: "Inter"
      fonts:
       - asset: "assets/fonts/Inter.ttf"
    - family: "Roboto"
      fonts:
       - asset: "assets/fonts/Roboto.ttf"
